version: "2"
services:
  softether:
    image: jedduff/softether-armhf
    container_name: softether
    ports:
      - 500:500/udp
      - 4500:4500/udp
      - 1701:1701/tcp
      - 443:443/tcp
      - 5555:5555/tcp
      - 992:992/tcp
    restart: unless-stopped
