version: "2"

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    # For DHCP it is recommended to remove these ports and instead add: network_mode: "host"
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
      - "4443:443/tcp"
    environment:
      TZ: 'America/Chicago'
      WEBPASSWORD: pihole1
    volumes:
       - './etc-pihole/:/home/pi/appdata/pihole/'
       - './etc-dnsmasq.d/:/home/pi/appdata pihole/dnsmasq.d/'
    # run `touch ./var-log/pihole.log` first unless you like errors
    # - './var-log/pihole.log:/var/log/pihole.log'
    dns:
      - 1.1.1.1
      - 1.0.0.1
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN
    restart: unless-stopped

## pass keyboard input and create variables for $TZ, $PASSWD, $DNS (possibly preset some dns servers and then create $GOOG, $CFLARE, etc)
